#!/usr/bin/env python3
import os, time

def default_interface():
    with open("/proc/net/route") as f:
        for line in f.readlines():
            if line.startswith("Iface"):
                continue
            iface = line.split()[0]
            return iface

def read_proc_net_dev():
    with open("/proc/net/dev") as f:
        return f.read()

def get_interface_stats(iface):
    for line in read_proc_net_dev().split("\n"):
        if iface in line:
            cols = line.split()
            return int(cols[1]), int(cols[9])

color_1 = os.environ['color_1']
color_2 = os.environ['color_2']
unit = os.environ['unit']
refresh_time = int(os.environ['refresh_time'])

#color_1 = '#9999FF'
#color_2 = '#CC99FF'
#unit = 'Mb'
#refresh_time = 1

factor = {"Kb": 1024/8,
          "KB": 1024,
          "Mb": 1024*1024/8,
          "MB": 1024*1024,
          "Gb": 1024*1024*1024/8,
          "GB": 1024*1024*1024}

scalar = factor.get(unit, 1024*1024/8) * refresh_time

iface = default_interface()

old_received, old_sent = get_interface_stats(iface)

while True:
    received, sent = get_interface_stats(iface)
    rx = (received - old_received) / scalar
    wx = (sent - old_sent) / scalar
    print(f'<span color=\'{color_1}\'>  </span>{rx:.1f}  <span color=\'{color_2}\'>  </span>{wx:.1f} {unit}/s', flush=True)
    old_received, old_sent = received, sent
    time.sleep(refresh_time)
