#!/home/aa/.envs/base/bin/python
import os, requests, functools

location = os.environ.get('location', 'Honolulu') # location
text = requests.get(f'http://wttr.in/{location}?format=%l:++%C%t+++%h').text.replace('+','')

if len(text) > 40: # probably error response
    exit

icons = {'Sunny':        ' ',
         'Overcast':     ' ',
         'Light rain':   ' ',
         'Drizzle':      ' ',
         'Rain':         ' ',
         'Shower':       ' ',
         'todo':         ' ',
         'Thunderstorm': ' ',
         'Mist':         ' ',
         'Fog':          ' ',
         'Haze':         ' ',
         'Snow':         ' '}

text = functools.reduce(lambda t, kv: t.replace(*kv), icons.items(), text)

print(text, flush=True)

